In [1]:
# import required libraries

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.shape

(50, 5)

In [4]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [5]:
df['State'] = le.fit_transform(df.State)


In [6]:
df.head()


R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [7]:

X =df.iloc[:,:-1].values


In [8]:

y= df.iloc[:,4:5].values

In [9]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [10]:
x_train.shape, x_test.shape

((35, 4), (15, 4))

In [11]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:

# creating ANN skeleton

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))  # dense - fully connected neurons
regressor.add(Dense(12,activation='relu')) # relu - avoiding linearity
regressor.add(Dense(8,activation='relu'))
regressor.add(Dense(9,activation='relu'))
regressor.add(Dense(1,activation='linear')) # as we are following linear regression (only for regression)

In [13]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss ='mse',metrics=['mse'] )

In [14]:
# training the model

regressor.fit(x_train,y_train,batch_size=10,epochs =300) # epoch - training the model 300 times , batch - first 10 observations

Epoch 1/300
4/4 [==============================] - 1s 7ms/step - loss: 14562252800.0000 - mse: 14562252800.0000
Epoch 2/300
4/4 [==============================] - 0s 4ms/step - loss: 14128915456.0000 - mse: 14128914432.0000
Epoch 3/300
4/4 [==============================] - 0s 5ms/step - loss: 13750553600.0000 - mse: 13750553600.0000
Epoch 4/300
4/4 [==============================] - 0s 4ms/step - loss: 13283437568.0000 - mse: 13283437568.0000
Epoch 5/300
4/4 [==============================] - 0s 3ms/step - loss: 12847890432.0000 - mse: 12847889408.0000
Epoch 6/300
4/4 [==============================] - 0s 3ms/step - loss: 12403562496.0000 - mse: 12403562496.0000
Epoch 7/300
4/4 [==============================] - 0s 3ms/step - loss: 11932116992.0000 - mse: 11932116992.0000
Epoch 8/300
4/4 [==============================] - 0s 4ms/step - loss: 11506488320.0000 - mse: 11506488320.0000
Epoch 9/300
4/4 [==============================] - 0s 4ms/step - loss: 10983412736.0000 - mse: 109834127

In [15]:
# testing the model

y_pred = regressor.predict(x_test)


1/1 [==============================] - 0s 69ms/step


In [16]:
from sklearn.metrics import r2_score

In [17]:
# evaluating the model with r2 score

r2_score(y_test,y_pred)

0.711915544061148

In [18]:
y_pred.flatten()

array([114292.875, 117762.05 , 119335.56 ,  58547.977, 173179.86 ,
       120113.234,  49275.594, 101086.57 , 115579.44 , 157689.97 ,
        88158.83 ,  75128.84 , 109217.36 , 102519.33 , 125871.7  ],
      dtype=float32)

In [19]:
# Comparing the actual and predicted y values

pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_value':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_value
0       103282.38      114292.875000
1       144259.40      117762.046875
2       146121.95      119335.562500
3        77798.83       58547.976562
4       191050.39      173179.859375
5       105008.31      120113.234375
6        81229.06       49275.593750
7        97483.56      101086.570312
8       110352.25      115579.437500
9       166187.94      157689.968750

In [20]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [21]:
# testing with random values

regressor.predict([[142107.34,91391.77,366168.42,2]])

1/1 [==============================] - 0s 27ms/step


array([[157690.3]], dtype=float32)

In [22]:
regressor.predict([[144107.12,118671.85,12345.42,0]])

1/1 [==============================] - 0s 25ms/step


array([[120692.8]], dtype=float32)

In [ ]:
# for ann classification, we have to encode the target column.