In [8]:
# Import required libraries

import pandas as pd
import numpy as np
import nltk

# nltk - natural language toolkit

import regex as re

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# Text processing

In [3]:
 a= "Hii all!!!! , I am a witcher and nice to meet you all"

In [4]:
# Remove all the special characters using Regex

In [11]:
reg = re.sub('[^a-zA-Z]',' ',a)
reg

'Hii all       I am a witcher and nice to meet you all'

In [12]:
# step 2 - make all characters either in lowercase or uppercase

In [13]:
lw = reg.lower()

In [14]:
lw

'hii all       i am a witcher and nice to meet you all'

In [15]:
# step 3: split the input

wd = lw.split()
wd

['hii',
 'all',
 'i',
 'am',
 'a',
 'witcher',
 'and',
 'nice',
 'to',
 'meet',
 'you',
 'all']

In [17]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [19]:
# step 4 : removing stopwords

new = [ i for i in wd if i not in set(stopwords.words('english')) ]
new

['hii', 'witcher', 'nice', 'meet']

In [20]:
# list comprehension
# syntax: [Expression/ output for interation in variables]

In [21]:
# step 5: stemming - short form of original words

ps = PorterStemmer()

In [23]:
p = [ps.stem(w) for w in new]
p

['hii', 'witcher', 'nice', 'meet']

In [28]:
# step 6: joining the words

t = ' '.join(p)
t

'hii witcher nice meet'

In [30]:
# step 7: convert text to numerical format

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

cv.fit_transform([t]).toarray()

array([[1, 1, 1, 1]])

In [32]:
df = pd.read_csv('/content/Restaurant_Reviews.tsv',delimiter='\t')

In [33]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [34]:
df.shape

(1000, 2)

In [37]:
data = [] # list

for i in range(0,1000):
  review = df['Review'][i] # reading the data
  review = re.sub('^[a-zA-Z]',' ',review) # removing special characters
  review = review.lower()
  review = review.split()
  review = [ ps.stem(w) for w in review if w not in set(stopwords.words('english'))] # stemming and removing stopwords
  review = ''.join(review) # joining all the words
  data.append(review) # for saving the result of the iteration


In [38]:
data

['ow...loveplace.',
 'rustgood.',
 'ottastitexturnasty.',
 'toplatemaybankholidayricksteverecommendloveit.',
 'selectmenugreatprices.',
 'owgetangriwantdamnpho.',
 'onesltitastfresh.)',
 'potatolikerubbercouldtellmadeaheadtimekeptwarmer.',
 'frigreattoo.',
 'greattouch.',
 'ervicprompt.',
 'ouldgoback.',
 'cashiercareeversaystillendwayyyoverpriced.',
 'tricapecodravoli,chicken,cranberry...mmmm!',
 'disgustprettisurehumanhair.',
 'shocksignindiccashonly.',
 'ighlirecommended.',
 'aitresslittlslowservice.',
 'placeworthtime,letalonvegas.',
 'idlikeall.',
 'burrittoblah!',
 'food,amazing.',
 'ervicalsocute.',
 'couldcareless...interiorbeautiful.',
 'performed.',
 "hat'right....thredvelvetcake.....ohhhstuffgood.",
 '-neverbroughtsaladaskfor.',
 'holewallgreatmexicanstreettacos,friendlistaff.',
 'ookhourgetfood4tablrestaurfoodlukewarm,severrunaroundliketotaloverwhelmed.',
 'worstsalmonsashimi.',
 'lsocombolikeburger,fries,beer23decentdeal.',
 'likefinalblow!',
 'foundplaceaccidcouldhappier.

In [41]:
x = cv.fit_transform(data).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
y = df['Liked'].values

In [42]:
# splitting data

from sklearn.model_selection import train_test_split

X_train, X_test , y_train,y_test = train_test_split(x,y,test_size= 0.3,random_state = 42)

### Model Building

In [43]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()

In [44]:
model.fit(X_train,y_train)

BernoulliNB()

In [45]:
y_pred = model.predict(X_test)

In [46]:
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [47]:
# Evaluting the model

from sklearn.metrics import accuracy_score

In [48]:
print(accuracy_score(y_test,y_pred))

0.5233333333333333


In [49]:
pd.crosstab(y_test,y_pred)

col_0   0    1
row_0         
0      10  142
1       1  147

In [50]:
import pickle

pickle.dump(model , open("review.pkl",'wb'))

# Model building with ANN

In [51]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [52]:
model1 = Sequential()
model1.add(Dense(1500,activation = 'relu'))
model1.add(Dense(3000,activation = 'relu'))
model1.add(Dense(1,activation = 'sigmoid'))

In [53]:
model1.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'])

In [54]:
model1.fit(x,y,epochs = 10)

Epoch 1/10
32/32 [==============================] - 6s 108ms/step - loss: 0.6941 - accuracy: 0.5180
Epoch 2/10
32/32 [==============================] - 3s 104ms/step - loss: 0.2096 - accuracy: 0.9990
Epoch 3/10
32/32 [==============================] - 3s 86ms/step - loss: 0.0112 - accuracy: 0.9970
Epoch 4/10
32/32 [==============================] - 3s 87ms/step - loss: 0.0058 - accuracy: 0.9990
Epoch 5/10
32/32 [==============================] - 3s 88ms/step - loss: 0.0073 - accuracy: 0.9990
Epoch 6/10
32/32 [==============================] - 4s 115ms/step - loss: 0.0064 - accuracy: 0.9980
Epoch 7/10
32/32 [==============================] - 3s 86ms/step - loss: 0.0045 - accuracy: 0.9990
Epoch 8/10
32/32 [==============================] - 3s 87ms/step - loss: 0.0031 - accuracy: 0.9980
Epoch 9/10
32/32 [==============================] - 3s 88ms/step - loss: 0.0037 - accuracy: 0.9990
Epoch 10/10
32/32 [==============================] - 3s 106ms/step - loss: 0.0046 - accuracy: 0.9980


In [55]:
model1.save('ann_review.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [68]:
## Testing the model using ANN

def new_review(new_review):
  new_review = new_review
  new_review = re.sub('[^a-zA-Z]',' ',new_review)
  new_review = new_review.lower()
  new_review = new_review.split(' ')
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_review =[ ps.stem(word) for word in new_review if not word in set(all_stopwords)]
  new_review = ' '.join(new_review)
  new_ = [new_review]
  new_X_test = cv.transform(new_).toarray()
  new_y_pred = model.predict(new_X_test)
  return new_y_pred

new_review = new_review(str(input("Enter the review ....")))

new_review


Enter the review ....i liked it


array([1])

In [70]:
if new_review[0] ==1:
  print("Liked")
else:
  print("Disliked")

Liked
